name: "Build and publish"

on:
  push:
    branches:
    - main
    tags:
    - 'v*'

env:
  PROJECT_PATH: 'AnimDL/AnimDL.csproj'
  CORE_PROJECT_PATH: 'AnimDL.Core/AnimDL.Core.csproj'
  PROJECT_NAME: 'AnimDL'
  PACKAGE_OUTPUT_DIRECTORY : ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
    deploy:
        name: 'Build and deploy'
        runs-on: 'windows-latest'
        steps:
        -   name: 'Checkout'
            uses: actions/checkout@v2
  
        -   name: 'Install dotnet'
            uses: actions/setup-dotnet@v1
            with:
                dotnet-version: '6.0'
  
        -   name: 'Restore packages'
            run: |
                dotnet restore ${{ env.PROJECT_PATH }}
                dotnet restore ${{ env.CORE_PROJECT_PATH}}

        -   name: 'Build project'
            run: | 
                dotnet build ${{ env.PROJECT_PATH }} --no-restore -c Release
                dotnet build ${{ env.CORE_PROJECT_PATH }} --no-restore -c Release

        -   name: 'Get version'
            id: version
            uses: battila7/get-version-action@v2    

        -   name: 'Pack'
            run: | 
                dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build -c Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v}} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
                dotnet pack ${{ env.CORE_PROJECT_PATH }} --no-restore --no-build -c Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v}} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

        -   name: 'Push'
            run: | 
                dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\${{ env.PROJECT_NAME }}.${{ steps.version.outputs.version-without-v }}.nupkg -s ${{ env.NUGET_SOURCE_URL }} -k ${{ secrets.NUGET_AUTH_TOKEN }}
                dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\${{ env.PROJECT_NAME }}.Core.${{ steps.version.outputs.version-without-v }}.nupkg -s ${{ env.NUGET_SOURCE_URL }} -k ${{ secrets.NUGET_AUTH_TOKEN }}